apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-quest-lvl-1-{{ team_name }}
  namespace: challs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-quest-lvl-1-{{ team_name }}
  template:
    metadata:
      labels:
        app: file-quest-lvl-1-{{ team_name }}
    spec:
      containers:
        - name: web
          image: docker.nexus.skyline.local:6000/file-quest-lvl-1:latest   # or build & push from the Dockerfile above
          imagePullPolicy: Always
          securityContext:
            runAsUser: 33         # www-data
            runAsGroup: 33
            readOnlyRootFilesystem: false