apiVersion: v1
kind: Service
metadata:
  name: file-quest-lvl-1-{{ team_name }}
  namespace: challs
spec:
  selector:
    app: file-quest-lvl-1-{{ team_name }}
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
