apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: file-quest-lvl-1-{{ team_name }}
  namespace: challs
spec:
  ingressClassName: traefik
  rules:
    - host: "{{ unique_name }}.skyline.local"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: file-quest-lvl-1-{{ team_name }}
                port:
                  number: 80
